@startuml
title OhMyLab Context Diagram

top to bottom direction

!include ../template/C4_Styles.puml

Person(user, "User", "People who use app")
Person(admin, "Admin", "Site administrator")

System(App, "App", "The platform ")
System(Auth, "Auth", "Auth for users")
System(Pgs, "Postgres", "Database")
System(Rds, "Redis", "Token cache")

Rel(user, App, "HTTPS")
Rel(admin, App, "HTTPS")
Rel(App, Pgs, "JDBC")
Rel(App, "Auth", "OAuth2")
Rel(Auth, "Rds", "RESP")

@enduml